app/Http/routes.php
<?php

use App\Category;
use App\Page;
use App\Product;
use App\Subproduct;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Event::listen('illuminate.query', function($query)
//{
//    var_dump($query);
//});
Route::get('qbo/oauth', 'QuickBookController@qboOauth');
Route::get('qbo/success', 'QuickBookController@qboSuccess');
Route::get('qbo/disconnect', 'QuickBookController@qboDisconnect');


Route::get('/', 'HomeController@index');
Route::group(['middleware' => 'auth'], function () {

    Route::get('category/new-arrivals', 'NewarrivalsController@show');
    Route::get('category/{slug}', 'CategoryController@show');
    Route::get('product/{slug}', 'ProductController@show');
    Route::post('/cart', 'CartController@cartadd');
    Route::post('/complete', 'CheckoutController@complete');

    Route::get('/cart', 'CartController@cart');

    Route::resource('add-client',  'AddClientController');

    Route::get('/checkout', 'CheckoutController@checkout');

    Route::get('/test', 'CheckoutController@test');


    Route::get('/cartIncDec', 'CartController@cartIncDec');

    Route::get('/cartDelete', 'CartController@cartDelete');

    Route::get('/clear-cart', 'CartController@clearcart');

    #Route::get('/complete', 'CheckoutController@complete');


    Route::get('/hide', 'PricesController@hide');
    Route::get('/wholesale', 'PricesController@wholesale');
    Route::get('/rrp', 'PricesController@rrp');
// Edit company info...
    Route::get('editprofile', 'ProfileController@index');
    Route::post('editprofile', 'ProfileController@update');


});

//Route::group(['middleware' => 'auth'],  function () {
//    Route::get('/Training_room', function () {
//        return view('training_room')->with('training', \App\TrainingRoom::find(0))->with('settings', Settings::find(0));
//    });
//});

// See App\Http\Kernel that has middleware AuthAdmin.
//
// We have two levels of validation. middleware auth is the standard 'Are you logged in', used above for the training room page.
// middleware admin uses Entrust to check that the logged in user has a role of 'Admin'.  See AuthAdmin.php for details.
// ;
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {

    Route::get('makethumbnailsfromexisting', 'admin\ImagesController@makethumbnailsfromexisting');

    Route::resource('/', 'admin\DashboardController');

    Route::resource('user', 'admin\UserController');

    Route::resource('manage', 'admin\DashboardController');

    Route::resource('dashboard', 'admin\DashboardController');

    Route::get('mappoints', 'admin\MapController@mappoints');

    Route::resource('map', 'admin\MapController');

    Route::resource('settings', 'admin\SettingsController');

    Route::post('type', 'admin\UserController@type');

    Route::post('filterstock',   'admin\StockController@filterstock');
    Route::get('stock',    'admin\StockController@index');
    Route::post('savereorder', 'admin\StockController@savereorder');

    Route::get('quantity', 'admin\QuantityController@index');
    Route::post('quantitychange',   'admin\QuantityController@quantitychange');
    Route::get('quantity/{repositionid}',    'admin\QuantityController@index');

    Route::post('quantity', 'admin\QuantityController@update');

    Route::post('quantityreorder', ['as' => 'quantityreorder', 'uses' => 'admin\ReorderController@quantity']);
    Route::post('updatequantityreorder', ['as' => 'updatequantityreorder', 'uses' => 'admin\ReorderController@update']);
//    Route::get('reorder', 'admin\ReorderController@index');




    // Liam Goldstein
    // New AJAX routes.

    Route::post('/api/quantity', 'admin\QuantityController@updateAJAX');
    Route::post('/api/savereorder', 'admin\StockController@savereorderAJAX');




    Route::resource('pages', 'admin\PagesController');

    Route::resource('homepage', 'admin\HomepageController');

    Route::resource('product', 'admin\ProductController');

    Route::post('delete_order', 'admin\OrderController@destroy');
    Route::resource('orders', 'admin\OrderController');
    Route::get('order/renew/{id}', 'admin\OrderController@renew');

    Route::resource('changecustomer', 'admin\ChangecustomerController');

    Route::post('updatecustomer', ['uses' => 'admin\ChangecustomerController@updatecustomer', 'as' => 'admin.updatecustomer'] );

    Route::post('invoice/extra/{id}',       'admin\InvoiceController@extra' );
    Route::get('generate_invoice/{id}',     'admin\InvoiceController@generate_invoice');
    Route::get('email_invoice/{id}',        'admin\InvoiceController@email_invoice');
    Route::get('view_invoice/{id}',         'admin\InvoiceController@view_invoice');
    Route::get('invoice/delete/{id}',       'admin\InvoiceController@order_delete');
    Route::post('order_deleteitem',         'admin\InvoiceController@order_deleteitem');

    //Route::get('images/{id}',               'admin\ImagesController@index');
    Route::post('imagecategory',            'admin\ImagesController@selectcat');
    Route::get('imagecategory',             'admin\ImagesController@index');
    Route::post('saveimage',                'admin\ImagesController@saveimage');

    Route::get('restoreimage/{id}',              'admin\ImagesController@restoreimage');
    Route::get('makecanvasbigger/{id}',         'admin\ImagesController@makecanvasbigger');

    Route::get('images/{id}/edit',          ['uses' => 'admin\ImagesController@edit', 'as' => 'admin.images.edit']);
    Route::resource('images',               'admin\ImagesController');

    //Route::resource('orderdetail', 'admin\OrderdetailController');

    Route::get('subproduct/{capital}', 'admin\SubproductController@index');

    Route::get('subproduct/create/{id}', 'admin\SubproductController@create');

    Route::resource('subproduct', 'admin\SubproductController');

    Route::resource('subproductdelete', 'admin\SubproductController');

    Route::get('/view_reorder/{id}',         'admin\StockController@view_reorder');

    Route::get('missing',   'admin\StockController@missing');
    Route::get('missingdownload',         'admin\StockController@view_missing');
    Route::get('stockreport', 'admin\StockController@stockreport');
    Route::get('stockreportdownload', 'admin\StockController@stockreportdownload');

    Route::get('recalc', 'admin\OrderController@recalc');
});




Route::get('/contact', function () {


    //This code gets "New Arrivals" from Product & Subproduct, puts them in a multidimensional array and then sorts them by date
    $product = Product::where('category_id', '=', 7)
        ->where('live', 1)
        ->get();

    $sub = Subproduct::with('product')->where('newarrival', 1)->where('splive', 1)
        ->orderBy('created_at', 'DESC')
        ->LIMIT(26)
        ->get();

    $newarrivals = array();
    foreach ($product as $p) {
        $newarrivals[] = array("image" => $p->image, "slug" => $p->slug, "sku" => $p->sku, "date" => $p->updated_at);

    }

    foreach ($sub as $p) {
        $newarrivals[] = array("image" => $p->image, "slug" => $p->product->slug, "sku" => $p->sku, "date" => $p->updated_at);
    }

    $date = array();
    foreach ($newarrivals as $key => $row) {
        $date[$key] = $row['date'];
    }
    array_multisort($date, SORT_DESC, $newarrivals);


    return View::make('contact')->with('newarrivals', $newarrivals)->with('category', Category::with('products')->orderBy('id')->get());
});

//Route::post('enquiry/', array(
//
//    'uses' => 'App\Http\Controllers\Api\v1\ContactUsController@postEnquiryForm'));



//Route::controllers([
////    'auth' => 'Auth\AuthController',
//    'password' => 'Auth\PasswordController',
//]);


// Authentication routes...     AuthenticatesUsers.php
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');



// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');



// Single page

Route::get('{slug}', array('as' => 'page', function($slug)
{
    $page = Page::where('slug', $slug)->first();

    //This code gets "New Arrivals" from Product & Subproduct, puts them in a multidimensional array and then sorts them by date
    $product = Product::where('category_id', '=', 7)
        ->where('live', 1)
        ->get();

    $sub = Subproduct::with('product')->where('newarrival', 1)->where('splive', 1)
        ->orderBy('created_at', 'DESC')
        ->LIMIT(26)
        ->get();

    $newarrivals = array();
    foreach ($product as $p) {
        $newarrivals[] = array("image" => $p->image, "slug" => $p->slug, "sku" => $p->sku, "date" => $p->updated_at);

    }

    foreach ($sub as $p) {
        $newarrivals[] = array("image" => $p->image, "slug" => $p->product->slug, "sku" => $p->sku, "date" => $p->updated_at);
    }

    $date = array();
    foreach ($newarrivals as $key => $row) {
        $date[$key] = $row['date'];
    }
    array_multisort($date, SORT_DESC, $newarrivals);


    if ( ! $page) App::abort(404, 'Page not found');

    $category = Category::with('products')
        ->with(array('products' => function ($query) {
            $query->where('live', '=', 1);
        }))

app/Http/Controllers/admin/SubproductController.php
<?php namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Product;
use App\Subproduct;
use App\Stone;
use App\Http\Requests;
use App\Http\Controllers\admin\ImagesController;

use Illuminate\Support\Facades\Auth;
use Krucas\Notification\Facades\Notification;
use Illuminate\Support\Facades\Redirect;

use Intervention\Image as Image;

use Illuminate\Http\Request;


class SubproductController extends Controller {

    public function index($id)
    {
        $product = Product::where('id', $id)->with('subproduct', 'category')->first();

        return \View::make('admin.subproduct.index')->with('product',$product) ;
    }

    public function create($id)
    {
        $stones = Stone::orderBy('stone', 'asc')->get();

        return \View::make('admin.subproduct.create')->with('categories',Category::all())->with('stones',$stones)
            ->with('product', Product::find($id));
    }
    public function store(Request $request)
    {
        $this->validate($request, [
//            'grossPrice' => 'required',
//            'into_safe' => 'required',
//            'quantity' => 'required',
            'stone_id' => 'required',
//            'image' => 'required',

        ]);

        $allowable_tags = '<br><br/><strong></strong><em></em><ul></ul><li></li>';

        $subproduct = new Subproduct;

        $product = Product::where('id', $request->input('id'))->first();


        $stone = Stone::where('id', $request->input('stone_id'))->first();

        $subproduct->sku = $product->sku . ' ' . $stone->code;
//        $subproduct->grossPrice = $request->input('grossPrice');
//        $subproduct->into_safe = $request->input('into_safe');

        $subproduct->fob = $request->input('fob');

        $subproduct->freight = round($subproduct->fob * .02, 2);
        if ($product->category->apply_bolt) {
            $subproduct->bolt = $product->category->bolt_amt;
        } else {
            $subproduct->bolt = 0;
        }
        $subproduct->hm = 1;
        $subproduct->into_safe = $subproduct->fob + $subproduct->freight + $subproduct->bolt + $subproduct->hm;
        $subproduct->grossPrice = $subproduct->into_safe * 2;

        $subproduct->quantity = $request->input('quantity');

        $subproduct->product_id = $product->id;
        $subproduct->stone_id = $request->input('stone_id');
        $subproduct->splive   = $request->input('splive');
        $subproduct->newarrival = $request->input('newarrival');
        $subproduct->image = 'currently-awaiting-image.jpg';
        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $filename = str_replace('£', '', $file->getClientOriginalName()) . ' - ' . time() . '.' . $file->getClientOriginalExtension();
            $path = public_path('images/products/' . $filename);
            //http://image.intervention.io/api/resize

            \Image::make($file->getRealPath())
                ->resize(1500, 1500, function ($constraint) {
                    $constraint->aspectRatio();
                })
                ->resizeCanvas(1500, 1500, 'center', false, 'ffffff')
                ->save($path);
            $subproduct->image = $filename;
            ImagesController::makethumbnail($filename);
        } else {
            $product->image = 'currently-awaiting-image.png';
        }
//        if (!$request->input('imageAlt')) {
//            $subproduct->imageAlt = $product->productName . ' image';
//        } else {
            $subproduct->imageAlt = $request->input('imageAlt') . ' - ' . $subproduct->sku ;
        //}
        $subproduct->save();

        Notification::success('The item was saved.');

        //return Redirect::route('admin.subproduct.index');
        //dd(redirect()->route('admin.subproduct.index', ['id' => 1]));
        return redirect('admin/subproduct/'. $product->id);
    }

    public function edit($id)
    {
        $subproduct = Subproduct::where('id',$id)->first();

        return \View::make('admin.subproduct.edit')->with('categories',Category::all())->with('stones', Stone::orderBy('stone', 'asc')->get())
            ->with('product', $subproduct);
    }

    public function update($id, request $request)
    {
        $this->validate($request, [
//            'grossPrice' => 'required',
//            'into_safe'  => 'required',
//            'quantity'   => 'required',
            'stone_id'   => 'required',
        ]);

        $allowable_tags = '<br><br/><strong></strong><em></em><ul></ul><li></li>';

        $subproduct = Subproduct::find($id);

        $product = Product::where('id',$subproduct->product_id)->first();

        $stone =   Stone::where('id', $request->input('stone_id'))->first();

        $subproduct->sku              = $product->sku . ' ' . $stone->code;
//        $subproduct->grossPrice       = $request->input('grossPrice');
//        $subproduct->into_safe        = $request->input('into_safe');
//        $subproduct->quantity         = $request->input('quantity');
        $subproduct->product_id       = $product->id;
        $subproduct->stone_id         = $request->input('stone_id');
        $subproduct->splive           = $request->input('splive');
        $subproduct->eoline           = $request->input('eoline');
        $subproduct->newarrival       = $request->input('newarrival');

        $subproduct->save();
//        if ($request->hasFile('image'))
//        {
//            $file = $request->file('image');
//            $filename  = str_replace('£', '', $file->getClientOriginalName()) . ' - ' . time() . '.' . $file->getClientOriginalExtension();
//            $path = public_path('images/products/' . $filename);
//            //http://image.intervention.io/api/resize
//
//            \Image::make($file->getRealPath())
////                ->resize(500, 500, function ($constraint) {
////                    $constraint->aspectRatio();
////                })
////                ->resizeCanvas(500,500, 'center', false, 'ffffff')
//                ->save($path);
//            $subproduct->image    			 = $filename;
//
//        }
//
//        $subproduct->imageAlt       = $request->input('imageAlt');

//        $subproduct->save();

        if ($request->hasFile('image'))
        {
            $file = $request->file('image');
            //$filename  = $file->getClientOriginalName() . ' - ' . time() . '.' . $file->getClientOriginalExtension();
            $filename = str_replace('£', '', $file->getClientOriginalName()) . ' - ' . time() . '.' . $file->getClientOriginalExtension();

            $path = public_path('images/products/' . $filename);
            //http://image.intervention.io/api/resize

            \Image::make($file->getRealPath())
                ->resize(2000,null, function ($constraint) {
                    $constraint->aspectRatio();
                })
                ->resizeCanvas(2000,2000, 'center', false, 'ffffff')
                ->save($path);

            $subproduct->image    			 = $filename;

            ImagesController::makethumbnail($filename);
        }

        $subproduct->imageAlt       = $request->input('imageAlt');
        $subproduct->save();

        Notification::success('The item was saved.');

        return redirect('admin/subproduct/'. $product->id);

    }

    public function destroy($id)
    {
        $subproduct = Subproduct::find($id);
        $product = Product::find($subproduct->product_id);
        $subproduct->delete();

        Notification::success('The item was deleted.');

        return redirect('admin/subproduct/'. $product->id);
    }


}

resources/views/admin/subproduct/create.blade.php
@extends('app')

@section('title', 'Products')

@section('content')

    @include('admin._partials.leftWrapper')

    <div id="rightWrapper">
        {{--<div id="header"><a id="fullPage" href="#">|||</a></div>--}}

        <h2>Create Product Option</h2>

        <style>
            .longerfield {
                width: 400px
            }

            .shorterfield {
                width: 80px;
            }
        </style>
        @include('admin._partials.notifications')

        {!! Form::open(array('route' => 'admin.subproduct.store', 'files' => true)) !!}

        <div class="form-group">
            {!!  Form::label('stone_id', 'Stone')  !!}
            <select name="stone_id" id="stone_id" required="required">
                <option value="">Select Stone...</option>
                @foreach($stones as $stone)
                    <option value="{{ $stone->id}}"> {{ $stone->stone}} </option>
                @endforeach
            </select>
        </div>

        <div class="control-group">
            {!! Form::label('splive', 'Live?') !!}
            <div style="width:90px" class="form-group">
                {!!Form::select('splive', array('1' => 'Yes','0' => 'No'), null, array('class' => 'form-control')) !!}
            </div>
        </div>

        <div class="control-group">
            {!! Form::label('newarrival', 'New Arrival') !!}
            <div style="width:70px" class="form-group">
                {!!Form::select('newarrival', array('0' => 'No', '1' => 'Yes'), null, array('class' => 'form-control')) !!}
            </div>
        </div>

        <div class="control-group">
            <div class="col-md-8">
                {{--<div class="col-md-4">--}}
                    {{--{!! Form::label('grossPrice', 'Gross Price') !!}--}}
                    {{--<div class="controls">--}}
                        {{--{!! Form::text('grossPrice', null, array('class' => 'shorterfield')) !!}--}}
                    {{--</div>--}}
                {{--</div>--}}
                <div class="col-md-6">
                    {!! Form::label('fob', 'FOB') !!}
                    <div class="controls">
                        {!! Form::text('fob', null, array('class' => 'shorterfield')) !!}
                    </div>
                </div>
                <div class="col-md-6">
                    {!! Form::label('quantity', 'Quantity') !!}
                    <div class="controls">
                        {!! Form::text('quantity', null, array('class' => 'shorterfield')) !!}
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="control-group">
            {!! Form::label('image', 'Image') !!}

            <div class="fileupload fileupload-new" data-provides="fileupload">
                <div class="fileupload-preview thumbnail" style="width: 200px; height: 150px;">
                    <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image">
                </div>
                <div>
                <span class="btn btn-file"><span class="fileupload-new">Select image</span><span
                            class="fileupload-exists">Change</span>{!! Form::file('image') !!}</span>
                    <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
                </div>
            </div>
        </div>

        {{--<div class="control-group">--}}
            {{--{!! Form::label('imageAlt', 'Image Alt Text') !!}--}}
            {{--<div class="controls">--}}
                {{--{!! Form::text('imageAlt') !!}--}}
            {{--</div>--}}
        {{--</div>--}}
        <input type="hidden" name="id" id="id"  value="{{ $product->id }}"/>
        <div class="form-actions">
            {!! Form::submit('Save', array('class' => 'btn btn-success btn-save btn-large')) !!}
            <a href="{{ URL::route('admin.product.index') }}" class="btn btn-large">Cancel</a>
        </div>

    {!! Form::close() !!}

@stop

resources/views/admin/subproduct/edit.blade.php
@extends('app')

@section('title', 'Products')

@section('content')
	@include('admin._partials.leftWrapper')

	<div id="rightWrapper">
		{{--<div id="header"><a id="fullPage" href="#">|||</a></div>--}}

	<h2>Edit Product {{ $product->sku }}</h2>

	@include('admin._partials.notifications')

	{!! Form::model($product, array('method' => 'put', 'route' => array('admin.subproduct.update', $product->id), 'files' => true)) !!}

		<div class="form-group">
			{!!  Form::label('stone_id', 'Stone')  !!}
			<select name="stone_id" id="stone_id" required="required">
				<option value="">Select Stone...</option>
				@foreach($stones as $stone)
					@if ($product->stone_id == $stone->id)
						<option value="{{ $stone->id }}" selected>{{ $stone->stone }}</option>
					@else
						<option value="{{  $stone->id }}">{{ $stone->stone }}</option>
					@endif
					{{--<option value="{{ $stone->id}}"> {{ $stone->stone}} </option>--}}
				@endforeach
			</select>
		</div>

		<div class="control-group">
			{!! Form::label('splive', 'Live?') !!}
			<div style="width:90px" class="form-group">
				{!!Form::select('splive', array('0' => 'No', '1' => 'Yes'), null, array('class' => 'form-control')) !!}
			</div>
		</div>
        <div class="control-group">
            {!! Form::label('eoline', 'End of Line?') !!}
            <div style="width:90px" class="form-group">
                {!!Form::select('eoline', array('0' => 'No', '1' => 'Yes'), null, array('class' => 'form-control')) !!}
            </div>
        </div>
		<div class="control-group">
			{!! Form::label('newarrival', 'New Arrival') !!}
			<div style="width:90px" class="form-group">
				{!!Form::select('newarrival', array('0' => 'No', '1' => 'Yes'), null, array('class' => 'form-control')) !!}
			</div>
		</div>

		{{--<div class="control-group">--}}
			{{--<div class="col-md-8">--}}
				{{--<div class="col-md-4">--}}
					{{--{!! Form::label('grossPrice', 'Gross Price') !!}--}}
					{{--<div class="controls">--}}
						{{--{!! Form::text('grossPrice', null, array('class' => 'shorterfield')) !!}--}}
					{{--</div>--}}
				{{--</div>--}}
				{{--<div class="col-md-6">--}}
					{{--{!! Form::label('into_safe', 'Nett Price') !!}--}}
					{{--<div class="controls">--}}
						{{--{!! Form::text('into_safe', null, array('class' => 'shorterfield')) !!}--}}
					{{--</div>--}}
				{{--</div>--}}
				{{--<div class="col-md-6">--}}
					{{--{!! Form::label('quantity', 'Quantity') !!}--}}
					{{--<div class="controls">--}}
						{{--{!! Form::text('quantity', null, array('class' => 'shorterfield')) !!}--}}
					{{--</div>--}}
				{{--</div>--}}
			{{--</div>--}}
		{{--</div>--}}

		<div class="clearfix"></div>

		<div class="control-group">
			{!! Form::label('image', 'Image') !!}

			<div class="fileupload fileupload-new" data-provides="fileupload">
				<div class="fileupload-preview thumbnail" style="width: 200px; height: 150px;">
					@if (!$product->image)
						<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image">
					@else
						<img src="/images/products/{{ $product->image }}">
					@endif
				</div>
				<div>
                <span class="btn btn-file"><span class="fileupload-new">Select image</span><span
							class="fileupload-exists">Change</span>{!! Form::file('image') !!}</span>
					<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
				</div>
			</div>
		</div>

		<div class="control-group">
			{!! Form::label('imageAlt', 'Image Alt Text') !!}
			<div class="controls">
				{!! Form::text('imageAlt') !!}
			</div>
		</div>



		<div class="form-actions">
			{!! Form::submit('Save', array('class' => 'btn btn-success btn-save btn-large')) !!}
			<a href="{{ URL::route('admin.product.index') }}" class="btn btn-large">Cancel</a>
		</div>
		<br/><br/><br/><br/><br/>
	{!! Form::close() !!}

@stop

resources/views/admin/subproduct/index.blade.php
@extends('app')

@section('title', 'Sub Products')

@section('content')
	@include('admin._partials.leftWrapper')

	<div id="rightWrapper">
		{{--<div id="header"><a id="fullPage" href="#">|||</a></div>--}}

	<h1>
		<a href="/admin/subproduct/create/{{ $product->id }}" class="btn btn-success"><i class="icon-plus-sign"></i> Add new product option</a>


	</h1>

		<h3>{{ $product->productName }} &nbsp; <img src="{{ '/images/products/' . $product->image }}" width="50" height="50"/> </h3>

	<hr>

	{!! Notification::showAll() !!}

	<table class="table table-striped">
		<thead>
			<tr>
				<th>Code</th>
				<th></th>

				<th>Quantity</th>
				<th>Price</th>
				<th>Nett Price</th>

				<th><i class="icon-cog"></i></th>
			</tr>
		</thead>
		<tbody>

			@foreach ($product->subproduct as $subproduct)
				<tr>

					<td style="padding-top:25px;">{{ $subproduct->sku }}</td>
					<td><img width="50" height="50" src="{{ '/images/products/thumbnails/' . $subproduct->image }}"></td>

					<td style="padding-top:25px;">{{ $subproduct->quantity }}</td>
					<td style="padding-top:25px;">{{ $subproduct->grossPrice }}</td>
					<td style="padding-top:25px;">{{ $subproduct->into_safe }}</td>

					<td style="padding-top:25px;">
						<a href="{{ URL::route('admin.subproduct.edit', $subproduct->id) }}" class="btn btn-success btn-mini pull-left">Edit</a>

						{{--{!! Form::open(array('route' => array('admin.subproduct.destroy', $subproduct->id), 'method' => 'delete', 'data-confirm' => 'Are you sure?')) !!}--}}
							{{--<button type="submit" href="{{ URL::route('admin.subproduct.destroy', $subproduct->id) }}" class="btn btn-danger btn-mini">Delete</button>--}}
						{{--{!! Form::close() !!}--}}


						{!!  Form::open(array('url' => 'admin/subproduct/' . $subproduct->id, 'class' => 'pull-right')) !!}
						{!! Form::hidden('_method', 'DELETE') !!}
						{!! Form::submit('Delete', array('class' => 'btn btn-warning confirmdelete')) !!}
						{!! Form::close() !!}

					</td>
				</tr>
			@endforeach
		</tbody>
	</table>
	<br/><br/><br/><br/>
@stop

resources/views/admin/subproduct/show.blade.php
@extends('app')

@section('title', 'Products')

@section('content')
	@include('admin._partials.leftWrapper')

	<div id="rightWrapper">
		{{--<div id="header"><a id="fullPage" href="#">|||</a></div>--}}
	<h2>Display continualdevelopment</h2>

	<hr>

	<h3>{{ $continualdevelopment->title }}</h3>
	<h5>@{{ $continualdevelopment->created_at }}</h5>
	{{ $continualdevelopment->body }}

	@if ($continualdevelopment->image)
		<hr>
		<figure><img src="{{ Image::resize($continualdevelopment->image, 800, 600) }}" alt=""></figure>
	@endif
@stop