app/Http/routes.php
<?php

use App\Category;
use App\Page;
use App\Product;
use App\Subproduct;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Event::listen('illuminate.query', function($query)
//{
//    var_dump($query);
//});
Route::get('qbo/oauth', 'QuickBookController@qboOauth');
Route::get('qbo/success', 'QuickBookController@qboSuccess');
Route::get('qbo/disconnect', 'QuickBookController@qboDisconnect');


Route::get('/', 'HomeController@index');
Route::group(['middleware' => 'auth'], function () {

    Route::get('category/new-arrivals', 'NewarrivalsController@show');
    Route::get('category/{slug}', 'CategoryController@show');
    Route::get('product/{slug}', 'ProductController@show');
    Route::post('/cart', 'CartController@cartadd');
    Route::post('/complete', 'CheckoutController@complete');

    Route::get('/cart', 'CartController@cart');

    Route::resource('add-client',  'AddClientController');

    Route::get('/checkout', 'CheckoutController@checkout');

    Route::get('/test', 'CheckoutController@test');


    Route::get('/cartIncDec', 'CartController@cartIncDec');

    Route::get('/cartDelete', 'CartController@cartDelete');

    Route::get('/clear-cart', 'CartController@clearcart');

    #Route::get('/complete', 'CheckoutController@complete');


    Route::get('/hide', 'PricesController@hide');
    Route::get('/wholesale', 'PricesController@wholesale');
    Route::get('/rrp', 'PricesController@rrp');
// Edit company info...
    Route::get('editprofile', 'ProfileController@index');
    Route::post('editprofile', 'ProfileController@update');


});

//Route::group(['middleware' => 'auth'],  function () {
//    Route::get('/Training_room', function () {
//        return view('training_room')->with('training', \App\TrainingRoom::find(0))->with('settings', Settings::find(0));
//    });
//});

// See App\Http\Kernel that has middleware AuthAdmin.
//
// We have two levels of validation. middleware auth is the standard 'Are you logged in', used above for the training room page.
// middleware admin uses Entrust to check that the logged in user has a role of 'Admin'.  See AuthAdmin.php for details.
// ;
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {

    Route::get('makethumbnailsfromexisting', 'admin\ImagesController@makethumbnailsfromexisting');

    Route::resource('/', 'admin\DashboardController');

    Route::resource('user', 'admin\UserController');

    Route::resource('manage', 'admin\DashboardController');

    Route::resource('dashboard', 'admin\DashboardController');

    Route::get('mappoints', 'admin\MapController@mappoints');

    Route::resource('map', 'admin\MapController');

    Route::resource('settings', 'admin\SettingsController');

    Route::post('type', 'admin\UserController@type');

    Route::post('filterstock',   'admin\StockController@filterstock');
    Route::get('stock',    'admin\StockController@index');
    Route::post('savereorder', 'admin\StockController@savereorder');

    Route::get('quantity', 'admin\QuantityController@index');
    Route::post('quantitychange',   'admin\QuantityController@quantitychange');
    Route::get('quantity/{repositionid}',    'admin\QuantityController@index');

    Route::post('quantity', 'admin\QuantityController@update');

    Route::post('quantityreorder', ['as' => 'quantityreorder', 'uses' => 'admin\ReorderController@quantity']);
    Route::post('updatequantityreorder', ['as' => 'updatequantityreorder', 'uses' => 'admin\ReorderController@update']);
//    Route::get('reorder', 'admin\ReorderController@index');




    // Liam Goldstein
    // New AJAX routes.

    Route::post('/api/quantity', 'admin\QuantityController@updateAJAX');
    Route::post('/api/savereorder', 'admin\StockController@savereorderAJAX');




    Route::resource('pages', 'admin\PagesController');

    Route::resource('homepage', 'admin\HomepageController');

    Route::resource('product', 'admin\ProductController');

    Route::post('delete_order', 'admin\OrderController@destroy');
    Route::resource('orders', 'admin\OrderController');
    Route::get('order/renew/{id}', 'admin\OrderController@renew');

    Route::resource('changecustomer', 'admin\ChangecustomerController');

    Route::post('updatecustomer', ['uses' => 'admin\ChangecustomerController@updatecustomer', 'as' => 'admin.updatecustomer'] );

    Route::post('invoice/extra/{id}',       'admin\InvoiceController@extra' );
    Route::get('generate_invoice/{id}',     'admin\InvoiceController@generate_invoice');
    Route::get('email_invoice/{id}',        'admin\InvoiceController@email_invoice');
    Route::get('view_invoice/{id}',         'admin\InvoiceController@view_invoice');
    Route::get('invoice/delete/{id}',       'admin\InvoiceController@order_delete');
    Route::post('order_deleteitem',         'admin\InvoiceController@order_deleteitem');

    //Route::get('images/{id}',               'admin\ImagesController@index');
    Route::post('imagecategory',            'admin\ImagesController@selectcat');
    Route::get('imagecategory',             'admin\ImagesController@index');
    Route::post('saveimage',                'admin\ImagesController@saveimage');

    Route::get('restoreimage/{id}',              'admin\ImagesController@restoreimage');
    Route::get('makecanvasbigger/{id}',         'admin\ImagesController@makecanvasbigger');

    Route::get('images/{id}/edit',          ['uses' => 'admin\ImagesController@edit', 'as' => 'admin.images.edit']);
    Route::resource('images',               'admin\ImagesController');

    //Route::resource('orderdetail', 'admin\OrderdetailController');

    Route::get('subproduct/{capital}', 'admin\SubproductController@index');

    Route::get('subproduct/create/{id}', 'admin\SubproductController@create');

    Route::resource('subproduct', 'admin\SubproductController');

    Route::resource('subproductdelete', 'admin\SubproductController');

    Route::get('/view_reorder/{id}',         'admin\StockController@view_reorder');

    Route::get('missing',   'admin\StockController@missing');
    Route::get('missingdownload',         'admin\StockController@view_missing');
    Route::get('stockreport', 'admin\StockController@stockreport');
    Route::get('stockreportdownload', 'admin\StockController@stockreportdownload');

    Route::get('recalc', 'admin\OrderController@recalc');
});




Route::get('/contact', function () {


    //This code gets "New Arrivals" from Product & Subproduct, puts them in a multidimensional array and then sorts them by date
    $product = Product::where('category_id', '=', 7)
        ->where('live', 1)
        ->get();

    $sub = Subproduct::with('product')->where('newarrival', 1)->where('splive', 1)
        ->orderBy('created_at', 'DESC')
        ->LIMIT(26)
        ->get();

    $newarrivals = array();
    foreach ($product as $p) {
        $newarrivals[] = array("image" => $p->image, "slug" => $p->slug, "sku" => $p->sku, "date" => $p->updated_at);

    }

    foreach ($sub as $p) {
        $newarrivals[] = array("image" => $p->image, "slug" => $p->product->slug, "sku" => $p->sku, "date" => $p->updated_at);
    }

    $date = array();
    foreach ($newarrivals as $key => $row) {
        $date[$key] = $row['date'];
    }
    array_multisort($date, SORT_DESC, $newarrivals);


    return View::make('contact')->with('newarrivals', $newarrivals)->with('category', Category::with('products')->orderBy('id')->get());
});

//Route::post('enquiry/', array(
//
//    'uses' => 'App\Http\Controllers\Api\v1\ContactUsController@postEnquiryForm'));



//Route::controllers([
////    'auth' => 'Auth\AuthController',
//    'password' => 'Auth\PasswordController',
//]);


// Authentication routes...     AuthenticatesUsers.php
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');



// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');



// Single page

Route::get('{slug}', array('as' => 'page', function($slug)
{
    $page = Page::where('slug', $slug)->first();

    //This code gets "New Arrivals" from Product & Subproduct, puts them in a multidimensional array and then sorts them by date
    $product = Product::where('category_id', '=', 7)
        ->where('live', 1)
        ->get();

    $sub = Subproduct::with('product')->where('newarrival', 1)->where('splive', 1)
        ->orderBy('created_at', 'DESC')
        ->LIMIT(26)
        ->get();

    $newarrivals = array();
    foreach ($product as $p) {
        $newarrivals[] = array("image" => $p->image, "slug" => $p->slug, "sku" => $p->sku, "date" => $p->updated_at);

    }

    foreach ($sub as $p) {
        $newarrivals[] = array("image" => $p->image, "slug" => $p->product->slug, "sku" => $p->sku, "date" => $p->updated_at);
    }

    $date = array();
    foreach ($newarrivals as $key => $row) {
        $date[$key] = $row['date'];
    }
    array_multisort($date, SORT_DESC, $newarrivals);


    if ( ! $page) App::abort(404, 'Page not found');

    $category = Category::with('products')
        ->with(array('products' => function ($query) {
            $query->where('live', '=', 1);
        }))

resources/views/admin/_partials/assets.blade.php
<link href="{{ URL::asset('assets/css/bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ URL::asset('assets/css/bootstrap-responsive.min.css') }}" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
<link href="{{ URL::asset('assets/css/main.css') }}" rel="stylesheet">
<link href="{{ URL::asset('assets/css/adminmain.css') }}" rel="stylesheet">
{{--<link href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" rel="stylesheet">--}}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
{{--<script src="//code.jquery.com/jquery-1.9.1.min.js"></script>--}}
<script src="{{ URL::asset('assets/js/bootstrap.min.js') }}"></script>
<script src="{{ URL::asset('assets/js/script.js?v=2') }}"></script>
{{--<script src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>--}}
<script type="text/javascript" src="https://appcenter.intuit.com/Content/IA/intuit.ipp.anywhere.js"></script>
<script type="text/javascript">
    intuit.ipp.anywhere.setup({
        menuProxy: '<?php print(env('QBO_MENU_URL')); ?>',
        grantUrl: '<?php print(env('QBO_OAUTH_URL')); ?>'
    });
</script>

resources/views/admin/_partials/header.blade.php
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a target="_blank" class="brand" href="/">Simon Alexander Website</a>

			@include('admin._partials.navigation')
		</div>
	</div>
</div>

<hr>

resources/views/admin/_partials/leftWrapper.blade.php
<div id="leftWrapper">
    <div id="listView" class="list">

        @if (Auth::user()->hasRole('admin'))
        <li><a class="dashboard" href="{{ URL::to('admin/dashboard') }}">Home</a></li>
        @endif

        <li><a class="product" href="{{ URL::to('admin/product') }}">Products</a></li>
        <li><a class="orders" href="{{ URL::to('admin/orders') }}">Orders</a></li>
        @if (Auth::user()->hasRole('admin') or Auth::user()->hasRole('assistantAdmin'))
            <li><a id="filterstock" class="stock" href="{{ URL::to('admin/stock') }}">Sales & Reorder</a></li>
            <li><a class="quantity" href="{{ URL::to('admin/quantity') }}">Prices & Quantity</a></li>
            <li><a class="user" href="{{ URL::to('admin/user') }}">Customers</a></li>
            <li><a class="map" href="{{ URL::to('admin/map') }}">Customer Map</a></li>
            <li><a class="pages" href="{{ URL::to('admin/pages') }}">Pages</a></li>
            <li><a class="settings" href="{{ URL::to('admin/settings') }}">Settings</a></li>
        @endif
        {{--<li><a class="reorder" href="{{ URL::to('admin/reorder') }}">Reorder</a></li>--}}
        <li><a class="images" href="{{ URL::to('admin/images') }}">Images</a></li>
    </div>
</div>

<script>


    $('.list li').removeClass('list-item-active');
    setNavigation();

    function setNavigation() {
        var path = window.location.pathname;
        path = path.replace(/\/$/, "");
        path = decodeURIComponent(path);

        $("#listView li a").each(function () {
            var href = $(this).attr('class');
            if (path.indexOf(href) >= 0) {
                $(this).closest('li').addClass('list-item-active');
            }
            if (path.indexOf("filterstock") >= 0 && href == 'stock') {
                $(this).closest('li').addClass("list-item-active");
            }
            if (path.indexOf("savereorder") >= 0 && href == 'stock') {
                $(this).closest('li').addClass("list-item-active");
            }
        });

    }


</script>

resources/views/admin/_partials/navigation.blade.php
{{--@if (Sentry::check())--}}
	<ul class="nav">
		{{--<li class="{{ Request::is('admin/pages*') ? 'active' : null }}"><a href="{{ URL::route('admin.pages.index') }}"><i class="icon-book"></i> Pages</a></li>--}}
		<li class="{{ Request::is('admin/manage') ? 'active' : null }}"><a href="{{ URL::route('admin.manage.index') }}"><i class="icon-book"></i> Manage</a></li>
		{{--<li class="{{ Request::is('admin/articles*') ? 'active' : null }}"><a href="{{ URL::route('admin.articles.index') }}"><i class="icon-edit"></i> Articles</a></li>--}}

		{{--<li><a href="{{ url('/auth/register') }}">Register</a></li>--}}

		<li><a href="{{ url('auth/logout') }}"><i class="icon-lock"></i> Logout</a></li>
	</ul>
{{--@endif--}}

resources/views/admin/_partials/notifications.blade.php
{!!   Notification::showAll() !!}

@if ($errors->any())
	<div class="alert alert-error">
		{{ implode('<br>', $errors->all()) }}
	</div>
@endif