app/Http/routes.php
<?php

use App\Category;
use App\Page;
use App\Product;
use App\Subproduct;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Event::listen('illuminate.query', function($query)
//{
//    var_dump($query);
//});
Route::get('qbo/oauth', 'QuickBookController@qboOauth');
Route::get('qbo/success', 'QuickBookController@qboSuccess');
Route::get('qbo/disconnect', 'QuickBookController@qboDisconnect');


Route::get('/', 'HomeController@index');
Route::group(['middleware' => 'auth'], function () {

    Route::get('category/new-arrivals', 'NewarrivalsController@show');
    Route::get('category/{slug}', 'CategoryController@show');
    Route::get('product/{slug}', 'ProductController@show');
    Route::post('/cart', 'CartController@cartadd');
    Route::post('/complete', 'CheckoutController@complete');

    Route::get('/cart', 'CartController@cart');

    Route::resource('add-client',  'AddClientController');

    Route::get('/checkout', 'CheckoutController@checkout');

    Route::get('/test', 'CheckoutController@test');


    Route::get('/cartIncDec', 'CartController@cartIncDec');

    Route::get('/cartDelete', 'CartController@cartDelete');

    Route::get('/clear-cart', 'CartController@clearcart');

    #Route::get('/complete', 'CheckoutController@complete');


    Route::get('/hide', 'PricesController@hide');
    Route::get('/wholesale', 'PricesController@wholesale');
    Route::get('/rrp', 'PricesController@rrp');
// Edit company info...
    Route::get('editprofile', 'ProfileController@index');
    Route::post('editprofile', 'ProfileController@update');


});

//Route::group(['middleware' => 'auth'],  function () {
//    Route::get('/Training_room', function () {
//        return view('training_room')->with('training', \App\TrainingRoom::find(0))->with('settings', Settings::find(0));
//    });
//});

// See App\Http\Kernel that has middleware AuthAdmin.
//
// We have two levels of validation. middleware auth is the standard 'Are you logged in', used above for the training room page.
// middleware admin uses Entrust to check that the logged in user has a role of 'Admin'.  See AuthAdmin.php for details.
// ;
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {

    Route::get('makethumbnailsfromexisting', 'admin\ImagesController@makethumbnailsfromexisting');

    Route::resource('/', 'admin\DashboardController');

    Route::resource('user', 'admin\UserController');

    Route::resource('manage', 'admin\DashboardController');

    Route::resource('dashboard', 'admin\DashboardController');

    Route::get('mappoints', 'admin\MapController@mappoints');

    Route::resource('map', 'admin\MapController');

    Route::resource('settings', 'admin\SettingsController');

    Route::post('type', 'admin\UserController@type');

    Route::post('filterstock',   'admin\StockController@filterstock');
    Route::get('stock',    'admin\StockController@index');
    Route::post('savereorder', 'admin\StockController@savereorder');

    Route::get('quantity', 'admin\QuantityController@index');
    Route::post('quantitychange',   'admin\QuantityController@quantitychange');
    Route::get('quantity/{repositionid}',    'admin\QuantityController@index');

    Route::post('quantity', 'admin\QuantityController@update');

    Route::post('quantityreorder', ['as' => 'quantityreorder', 'uses' => 'admin\ReorderController@quantity']);
    Route::post('updatequantityreorder', ['as' => 'updatequantityreorder', 'uses' => 'admin\ReorderController@update']);
//    Route::get('reorder', 'admin\ReorderController@index');




    // Liam Goldstein
    // New AJAX routes.

    Route::post('/api/quantity', 'admin\QuantityController@updateAJAX');
    Route::post('/api/savereorder', 'admin\StockController@savereorderAJAX');




    Route::resource('pages', 'admin\PagesController');

    Route::resource('homepage', 'admin\HomepageController');

    Route::resource('product', 'admin\ProductController');

    Route::post('delete_order', 'admin\OrderController@destroy');
    Route::resource('orders', 'admin\OrderController');
    Route::get('order/renew/{id}', 'admin\OrderController@renew');

    Route::resource('changecustomer', 'admin\ChangecustomerController');

    Route::post('updatecustomer', ['uses' => 'admin\ChangecustomerController@updatecustomer', 'as' => 'admin.updatecustomer'] );

    Route::post('invoice/extra/{id}',       'admin\InvoiceController@extra' );
    Route::get('generate_invoice/{id}',     'admin\InvoiceController@generate_invoice');
    Route::get('email_invoice/{id}',        'admin\InvoiceController@email_invoice');
    Route::get('view_invoice/{id}',         'admin\InvoiceController@view_invoice');
    Route::get('invoice/delete/{id}',       'admin\InvoiceController@order_delete');
    Route::post('order_deleteitem',         'admin\InvoiceController@order_deleteitem');

    //Route::get('images/{id}',               'admin\ImagesController@index');
    Route::post('imagecategory',            'admin\ImagesController@selectcat');
    Route::get('imagecategory',             'admin\ImagesController@index');
    Route::post('saveimage',                'admin\ImagesController@saveimage');

    Route::get('restoreimage/{id}',              'admin\ImagesController@restoreimage');
    Route::get('makecanvasbigger/{id}',         'admin\ImagesController@makecanvasbigger');

    Route::get('images/{id}/edit',          ['uses' => 'admin\ImagesController@edit', 'as' => 'admin.images.edit']);
    Route::resource('images',               'admin\ImagesController');

    //Route::resource('orderdetail', 'admin\OrderdetailController');

    Route::get('subproduct/{capital}', 'admin\SubproductController@index');

    Route::get('subproduct/create/{id}', 'admin\SubproductController@create');

    Route::resource('subproduct', 'admin\SubproductController');

    Route::resource('subproductdelete', 'admin\SubproductController');

    Route::get('/view_reorder/{id}',         'admin\StockController@view_reorder');

    Route::get('missing',   'admin\StockController@missing');
    Route::get('missingdownload',         'admin\StockController@view_missing');
    Route::get('stockreport', 'admin\StockController@stockreport');
    Route::get('stockreportdownload', 'admin\StockController@stockreportdownload');

    Route::get('recalc', 'admin\OrderController@recalc');
});




Route::get('/contact', function () {


    //This code gets "New Arrivals" from Product & Subproduct, puts them in a multidimensional array and then sorts them by date
    $product = Product::where('category_id', '=', 7)
        ->where('live', 1)
        ->get();

    $sub = Subproduct::with('product')->where('newarrival', 1)->where('splive', 1)
        ->orderBy('created_at', 'DESC')
        ->LIMIT(26)
        ->get();

    $newarrivals = array();
    foreach ($product as $p) {
        $newarrivals[] = array("image" => $p->image, "slug" => $p->slug, "sku" => $p->sku, "date" => $p->updated_at);

    }

    foreach ($sub as $p) {
        $newarrivals[] = array("image" => $p->image, "slug" => $p->product->slug, "sku" => $p->sku, "date" => $p->updated_at);
    }

    $date = array();
    foreach ($newarrivals as $key => $row) {
        $date[$key] = $row['date'];
    }
    array_multisort($date, SORT_DESC, $newarrivals);


    return View::make('contact')->with('newarrivals', $newarrivals)->with('category', Category::with('products')->orderBy('id')->get());
});

//Route::post('enquiry/', array(
//
//    'uses' => 'App\Http\Controllers\Api\v1\ContactUsController@postEnquiryForm'));



//Route::controllers([
////    'auth' => 'Auth\AuthController',
//    'password' => 'Auth\PasswordController',
//]);


// Authentication routes...     AuthenticatesUsers.php
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');



// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');



// Single page

Route::get('{slug}', array('as' => 'page', function($slug)
{
    $page = Page::where('slug', $slug)->first();

    //This code gets "New Arrivals" from Product & Subproduct, puts them in a multidimensional array and then sorts them by date
    $product = Product::where('category_id', '=', 7)
        ->where('live', 1)
        ->get();

    $sub = Subproduct::with('product')->where('newarrival', 1)->where('splive', 1)
        ->orderBy('created_at', 'DESC')
        ->LIMIT(26)
        ->get();

    $newarrivals = array();
    foreach ($product as $p) {
        $newarrivals[] = array("image" => $p->image, "slug" => $p->slug, "sku" => $p->sku, "date" => $p->updated_at);

    }

    foreach ($sub as $p) {
        $newarrivals[] = array("image" => $p->image, "slug" => $p->product->slug, "sku" => $p->sku, "date" => $p->updated_at);
    }

    $date = array();
    foreach ($newarrivals as $key => $row) {
        $date[$key] = $row['date'];
    }
    array_multisort($date, SORT_DESC, $newarrivals);


    if ( ! $page) App::abort(404, 'Page not found');

    $category = Category::with('products')
        ->with(array('products' => function ($query) {
            $query->where('live', '=', 1);
        }))

app/User.php
<?php

namespace App;

use Zizaco\Entrust\Traits\EntrustUserTrait;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract
{
    use Authenticatable, CanResetPassword, EntrustUserTrait;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password, username', 'name2'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }
    public function address()
    {
        return $this->hasOne('App\Address', 'user_id', 'id');
    }
    public function is($roleName)
    {
        foreach ($this->roles()->get() as $role)
        {
            if ($role->name == $roleName)
            {
                return true;
            }
        }

        return false;
    }

}

resources/views/admin/user/create.blade.php
@extends('app')

@section('title', 'Customers')

@section('content')

    <style>
        .form-group {
            margin-bottom: 0;
        }
    </style>
    @include('admin._partials.leftWrapper')

    <div id="rightWrapper">
        {{--<div id="header"><a id="fullPage" href="#">|||</a></div>--}}
        <div id="contentWrapper">
            <h2>Create Customer</h2>

            <style>
                .longerfield {
                    width: 400px
                }

                .shorterfield {
                    width: 80px;
                }
            </style>
            @include('admin._partials.notifications')

            {!! Form::open(array('route' => 'admin.user.store')) !!}

            <div class="form-group">
                <label class="col-md-2 control-label">Username</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" name="username"
                           value="{{ old('username') }}">
                </div>
            </div>
            <div style="clear:both;height:1px"></div>


            <div class="form-group">
                <label class="col-md-2 control-label">Contact Name 1</label>
                <div class="col-md-4">
                    <input required  type="text" class="form-control" name="name2"
                           value="{{ old('name2') }}">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Contact Role 1</label>
                <div class="col-md-4">
                    <input required  type="text" class="form-control" name="name2_role"
                           value="{{ old('name2_role') }}">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Contact Name 2</label>
                <div class="col-md-4">
                    <input  type="text" class="form-control" name="name3"
                           value="{{ old('name3') }}">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Contact Role 2</label>
                <div class="col-md-4">
                    <input  type="text" class="form-control" name="name3_role"
                           value="{{ old('name3_role') }}">
                </div>
            </div>
<style>
    .reduce {width:150px}
</style>
            <div style="clear:both;height:1px"></div>
            <div class="form-group">
                <label class="col-md-2 control-label">Customer Type</label>
                <div class="col-md-10">
                    {!! Form::select('type', array('0' => 'Simon', '3' => 'Demelza', '2' => 'Target'),
                         null, array('class' => 'form-control reduce')) !!}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Customer or Agent</label>
                <div class="col-md-10">
                    {!! Form::select('agent', array('0' => 'Customer', '1' => 'Agent'),
                         null, array('class' => 'form-control reduce')) !!}
                </div>
            </div>
            <div style="clear: both"></div>

            <div style="margin-top:10px" class="form-group">
                <label class="col-md-2 control-label">E-Mail Address</label>
                <div class="col-md-4">
                    <input  type="email" class="form-control" name="email"
                           value="{{ old('email') }}">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Company Name</label>
                <div class="col-md-4">
                    <input  type="text" class="form-control" name="companyName"
                           value="{{ old('companyName') }}">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Password</label>
                <div class="col-md-4">
                    <input  type="password" class="form-control" name="password">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Confirm Password</label>
                <div class="col-md-4">
                    <input  type="password" class="form-control"
                           name="password_confirmation">
                </div>
            </div>

            <div style="clear:both;height:1px"></div>

                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">
                        Register
                    </button>
                </div>
            <br/><br/><br/>
            <div class="form-group">
                <label class="col-md-2 control-label">Address 1</label>
                <div class="col-md-4">
                    <input  type="text" class="form-control" name="address1"
                           value="{{ old('address1') }}">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Address 2</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" name="address2" value="{{ old('address2') }}">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Town/City</label>
                <div class="col-md-4">
                    <input  type="text" class="form-control" name="town"
                           value="{{ old('town') }}">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">County</label>
                <div class="col-md-4">
                    <input  type="text" class="form-control" name="county"
                           value="{{ old('county') }}">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Postcode</label>
                <div class="col-md-4">
                    <input  type="text" class="form-control" name="postcode"
                           value="{{ old('postcode') }}">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Telephone</label>
                <div class="col-md-4">
                    <input type="text" class="form-control"  name="phone" value="{{ old('phone') }}">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">VAT number</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" name="vat" value="{{ old('vat') }}">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Company Number</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" name="companyID" value="{{ old('companyID') }}">
                </div>
            </div>


            <div class="form-group">
                <label class="col-md-2 control-label">Notes</label>
                <div class="col-md-10">
                    <textarea rows="6" class="form-control" cols="150" name="notes">{{ old('notes') }}</textarea>

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">
                        Register
                    </button>
                </div>
            </div>


            {!! Form::close() !!}
        </div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('app')

@section('title', 'Customers')

@section('content')
    @include('admin._partials.leftWrapper')

    <div id="rightWrapper">
        {{--<div id="header"><a id="fullPage" href="#">|||</a></div>--}}
        <div id="contentWrapper">

            <h2>Edit Customer <span style="color:red">{!! $user->name !!} </span> </h2>

            @include('admin._partials.notifications')

            {!! Form::model($user, array('method' => 'put', 'route' => array('admin.user.update', $user->id), 'files' => true)) !!}
<style>
    .form-group {
        margin-bottom: 0;
    }
</style>
            <div class="form-group">
                <label class="col-md-2 control-label">Username</label>
                <div class="col-md-4">
                    {!! Form::text('username', null, array('class' => 'form-control','required')) !!}
                </div>
            </div>

            <div style="clear:both;height:1px"></div>

            <div class="form-group">
                <label class="col-md-2 control-label">Contact Name 1</label>
                <div class="col-md-4">
                    {!! Form::text('name2', isset($user->name2) ? $user->name2 : null, array( 'class'=>'form-control','required' )) !!}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Contact Role 1</label>
                <div class="col-md-4">
                    {!! Form::text('name2_role', isset($user->name2_role) ? $user->name2_role : null, array( 'class'=>'form-control','required' )) !!}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Contact Name 2</label>
                <div class="col-md-4">
                    {!! Form::text('name3', isset($user->name3) ? $user->name3 : null, array( 'class'=>'form-control' )) !!}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Contact Role 2</label>
                <div class="col-md-4">
                    {!! Form::text('name3_role', isset($user->name3_role) ? $user->name3_role : null, array( 'class'=>'form-control' )) !!}
                </div>
            </div>
            <style>
                .reduce {width:150px}
            </style>

            <div class="form-group">
                <label class="col-md-2 control-label">Customer Type</label>
                <div class="col-md-10">
                    {!! Form::select('type', array('0' => 'Simon', '3' => 'Demelza', '2' => 'Target'),
                         null, array('class' => 'form-control reduce')) !!}
                </div>
            </div>


            <div class="form-group">
                <label class="col-md-2 control-label">Customer Authorised</label>
                <div class="col-md-10">
                    {!! Form::select('confirmed', array('0' => 'Yes', '1' => 'No'),
                         null, array('class' => 'form-control reduce')) !!}
                </div>
            </div>

            <div style="clear: both"></div>

            <div style="margin-top:20px" class="form-group">
                <label class="col-md-2 control-label">Email</label>
                <div class="col-md-4">
                    {!! Form::text('email', null, array('class' => 'form-control')) !!}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Company Name</label>
                <div class="col-md-4">

                    {!! Form::text('companyName', isset($user->address->companyName) ? $user->address->companyName : null, array( 'class'=>'form-control', 'required' )) !!}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Password</label>
                <div class="col-md-4">
                    <input type="password" class="form-control" name="password">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Confirm Password</label>
                <div class="col-md-4">
                    <input type="password" class="form-control" name="password_confirmation">
                </div>
            </div>


            <div class="clearfix"></div>
            <div class="form-actions">
                {!! Form::submit('Save', array('class' => 'btn btn-success btn-save btn-large')) !!}
                <a href="{{ URL::route('admin.user.index') }}" class="btn btn-large">Cancel</a>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Address 1</label>
                <div class="col-md-4">


                    {!! Form::text('address1', isset($user->address->address1) ? $user->address->address1 : null, array( 'class'=>'form-control' )) !!}

                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Address 2</label>
                <div class="col-md-4">

                    {!! Form::text('address2', isset($user->address->address2) ? $user->address->address2 : null, array( 'class'=>'form-control' )) !!}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Town/City</label>
                <div class="col-md-4">


                    {!! Form::text('town', isset($user->address->town) ? $user->address->town : null, array( 'class'=>'form-control' )) !!}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">County</label>
                <div class="col-md-4">

                    {!! Form::text('county', isset($user->address->county) ? $user->address->county : null, array( 'class'=>'form-control' )) !!}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Postcode</label>
                <div class="col-md-4">

                    {!! Form::text('postcode', isset($user->address->postcode) ? $user->address->postcode : null, array( 'class'=>'form-control' )) !!}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Telephone</label>
                <div class="col-md-4">


                    {!! Form::text('phone', isset($user->address->phone) ? $user->address->phone : null, array( 'class'=>'form-control' )) !!}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">VAT number</label>
                <div class="col-md-4">

                    {!! Form::text('vat', isset($user->address->vat) ? $user->address->vat : null, array( 'class'=>'form-control' )) !!}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Company Number</label>
                <div class="col-md-4">
                    {!! Form::text('companyID', isset($user->address->companyID) ? $user->address->companyID : null, array( 'class'=>'form-control' )) !!}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Notes</label>
                <div class="col-md-10">
                    <textarea rows="6" class="form-control" cols="150" name="notes">{{ isset($user->notes) ? $user->notes : null }}</textarea>

                </div>
            </div>

            <div class="clearfix"></div>
            <div class="form-actions">
                {!! Form::submit('Save', array('class' => 'btn btn-success btn-save btn-large')) !!}
                <a href="{{ URL::route('admin.user.index') }}" class="btn btn-large">Cancel</a>
            </div>

            {!! Form::close() !!}
            <br/><br/><br/><br/>
        </div>
        </div>
        <br/><br/><br/><br/>
@endsection

resources/views/admin/user/index.blade.php
@extends('app')

@section('title', 'Customers')

@section('content')

    @include('admin._partials.leftWrapper')

    <div id="rightWrapper">
        {{--<div id="header"><a id="fullPage" href="#">|||</a></div>--}}
    <div id="contentWrapper">


        <h1>
            Customers &nbsp;<a href="{{ URL::route('admin.user.create') }}" class="btn btn-success"><i
                        class="icon-plus-sign"></i> Add new Customer</a>
        </h1>

        <hr>

        {!!   Notification::showAll() !!}

        {!! Form::open(array('action' => 'admin\UserController@type')) !!}

        <table>
            <tr>
                <td width="260"><strong>Select Customer Type</strong></td>

            </tr>
            <tr>
                <td><select id="form1_type" name="type" class="autosubmit">
                        <option value="">Please Select</option>
                        <option value="0">Simon</option>
                        <option value="1">Max</option>
                        <option value="2">Target</option>

                    </select></td>

            </tr>
        </table>


        <input type="submit" value="Submit">
        {!! Form::close() !!}
        <br/><br/>

        <table class="table table-striped">
            <thead>
            <tr>

                <th>#</th>
                <th>Username</th>
                <th>Company</th>
                <th>Name</th>
                <th>Logins</th>
                <th>E-mail</th>
                {{--<th>Confirmed</th>--}}
                <th width="120"><i class="icon-cog"></i></th>
            </tr>
            </thead>
            <tbody>

            @foreach ($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td><a href="{{ URL::route('admin.user.edit', $user->id) }}">{{ $user->username }}</a></td>
                    <td><a href="{{ URL::route('admin.user.edit', $user->id) }}">{{ $user->address->companyName }}</a></td>
                    <td><a href="{{ URL::route('admin.user.edit', $user->id) }}">{{ $user->name2 }}</a></td>
                    <td><a href="{{ URL::route('admin.user.edit', $user->id) }}">{{ $user->logins }}</a></td>
                    <td>{{ $user->email }}</td>
                    {{--<td>@if ($user->confirmed == 1) NO  @endif</td>--}}
                    <td>
                        <a href="{{ URL::route('admin.user.edit', $user->id) }}"
                           class="btn btn-success btn-mini pull-left">Edit</a>

                        {!! Form::open(array('route' => array('admin.user.destroy', $user->id), 'method' => 'delete', 'data-confirm' => 'Are you sure?')) !!}
                        <button type="submit" href="{{ URL::route('admin.user.destroy', $user->id) }}"
                                class="btn btn-danger btn-mini">Delete
                        </button>
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <br/><br/><br/>

    </div>
@endsection

resources/views/admin/user/show.blade.php
@extends('app')

@section('title', 'Users')

@section('content')
	@include('admin._partials.leftWrapper')

	<div id="rightWrapper">
		{{--<div id="header"><a id="fullPage" href="#">|||</a></div>--}}
	<div id="contentWrapper">
	<h2>Display continualdevelopment</h2>

	<hr>

	<h3>{{ $continualdevelopment->title }}</h3>
	<h5>@{{ $continualdevelopment->created_at }}</h5>
	{{ $continualdevelopment->body }}

	@if ($continualdevelopment->image)
		<hr>
		<figure><img src="{{ Image::resize($continualdevelopment->image, 800, 600) }}" alt=""></figure>
	@endif
</div>
@endsection